import Head from 'next/head';

const Home = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a href="http://localhost:8080/login/discord">Discord Login</a>
    </div>
  );
};

export default Home;
