# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run NPM CI Frontend
      run: npm ci
      working-directory: frontend
    - name: Build Frontend
      run: npm run build
      working-directory: frontend
    - name: Run NPM CI GraphQL
      run: npm ci
      working-directory: graphql
    - name: Build GraphQL
      run: npm run build
      working-directory: graphql
    - name: SSH Deploy Frontend
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # Source directory
        SOURCE: 'frontend'
        # Target directory
        TARGET: ${{ secrets.TARGET }}
    - name: SSH Deploy GraphQL
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # Source directory
        SOURCE: 'graphql/dist/'
        # Target directory
        TARGET: ${{ secrets.TARGET_GRAPHQL }}
